//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÄlytaloWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaloValo
    {
        public int Valo_ID { get; set; }
        public string Huone { get; set; }
        public string ValaisinType { get; set; }
        public string Lamppu_ID { get; set; }
        public Nullable<int> ValoTila_ID { get; set; }
        public string ValonMaara { get; set; }
        public Nullable<System.DateTime> ValoTilaKirjattu { get; set; }
    }
}
