//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÄlytaloWEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TaloSauna
    {
        public int Sauna_ID { get; set; }
        public string SaunaTavoiteLampotila { get; set; }
        public string SaunaNykyLampotila { get; set; }
        public Nullable<bool> SaunanTila { get; set; }

        //Lisätty 19.8.2016-->
        [Display(Name = "saunatilakirjattu")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> SaunaTilaKirjattu { get; set; }
        public Nullable<int> Saunan_ID { get; set; }
        public string SaunanNimi { get; set; }
    }
}
